# Generated by Django 5.0.7 on 2024-08-21 21:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_tailor_alter_chatmessage_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='tailor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
