# Generated by Django 5.0.7 on 2024-08-21 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_tailor_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tailor',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='tailor',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=10),
        ),
    ]
